"""initial_migration

Revision ID: f4f0a0f0519d
Revises: 
Create Date: 2022-09-05 23:27:58.259790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils
from src.back.tables.telemetry import ParamType

# revision identifiers, used by Alembic.
revision = 'f4f0a0f0519d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry',
    sa.Column('well_id', postgresql.UUID(as_uuid=True), nullable=False, comment='id скважины'),
    sa.Column('well_name', sa.String(), nullable=True, comment='название скважины'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Дата создания записи'),
    sa.Column('measured_at', sa.DateTime(), nullable=False, comment='Дата замера параметра'),
    sa.Column('parameter', sqlalchemy_utils.types.choice.ChoiceType(ParamType), nullable=False, comment='Параметр'),
    sa.Column('value', sa.Float(), nullable=True, comment='Значение параметра'),
    sa.PrimaryKeyConstraint('well_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telemetry')
    # ### end Alembic commands ###
