"""Added Users and Chat tables

Revision ID: 26090bcb2c11
Revises: 07ea4e2c1209
Create Date: 2022-09-15 16:25:19.311354

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '26090bcb2c11'
down_revision = '07ea4e2c1209'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_room',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, comment='Идентификатор записи'),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Идентификатор записи'),
    sa.Column('email', sa.String(), nullable=True, comment='Email адрес'),
    sa.Column('name', sa.String(), nullable=True, comment='Имя пользователя'),
    sa.Column('hashed_password', sa.String(), nullable=True, comment='Зашифрованный пароль'),
    sa.Column('company_name', sa.String(), nullable=True, comment='Название компании'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Время создания записи'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('chat_message',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, comment='Идентификатор записи'),
    sa.Column('room_id', postgresql.UUID(as_uuid=True), nullable=True, comment='Идентификатор комнаты чата'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='Идентификатор пользователя'),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Время создания записи'),
    sa.ForeignKeyConstraint(['room_id'], ['chat_room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_message')
    op.drop_table('user')
    op.drop_table('chat_room')
    # ### end Alembic commands ###
