"""empty message

Revision ID: 68ec44b601a9
Revises: f4f0a0f0519d
Create Date: 2022-09-07 22:35:35.109240

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '68ec44b601a9'
down_revision = 'f4f0a0f0519d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, comment='id скважины'))
    op.drop_column('telemetry', 'well_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry', sa.Column('well_id', postgresql.UUID(), autoincrement=False, nullable=False, comment='id скважины'))
    op.drop_column('telemetry', 'id')
    # ### end Alembic commands ###
