version: "3.9"
services:
  drill-postgres:
    image: postgres:13.3
    container_name: drill-postgres
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - ./postgresql:/var/lib/postgresql
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_PASSWORD: superuser
    ports:
      - "5432:5432"